import {type ReactElement, Suspense} from 'react';
import './globals.css';
import {Skeleton} from '@/components/ui/skeleton';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({children}: { children: ReactElement }) {
    "use server"
    return (
        <html lang="en">
            <body>
                <Suspense fallback={<Skeleton/>}>
                    {children}
                </Suspense>
            </body>
        </html>
    );
}
